answer = int(input("Give a whole number that is less than 5.\n"))
print(answer < 5)
answer_2 = int(input("Give a whole number that is equal to 16.\n"))
print(answer_2 == 16)
answer_3 = int(input("Give a whole number that is greater than 100.\n"))
print(answer_3 > 100)
answer_4 = int(input("Give a whole number that is greater than or equal to 11.\n"))
print(answer_4 >= 11)
answer_5 = int(input("Give a whole number that is less than or equal to 3.\n"))
print(answer_5 <= 3)
answer_6 = int(input("Give a whole number that is greater than 4 and less than 6.\n"))
print(answer_6 > 4 and answer_6 < 6)